import os
import csv
import json
import tempfile
import base64
from typing import List, Dict, Any

# Configure Matplotlib to run headlessly
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ReportLab imports for PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to add 'Page X of Y' footers and headers to every page except the cover page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            super().showPage()
        super().save()

    def draw_page_elements(self, page_count):
        # Skip header/footer on the cover page (Page 1)
        if self._pageNumber == 1:
            return

        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b")) # Slate-500

        # Header
        self.drawString(54, 750, "CROP HEALTH ANALYSIS REPORT — SCIENTIFIC AI SUMMARY")
        self.setStrokeColor(colors.HexColor("#cbd5e1")) # Slate-300
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)

        # Footer
        self.line(54, 45, 558, 45)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 30, page_text)
        self.drawString(54, 30, "Generated by AI Crop Health Analysis System — Model v4.1 (ResNet-50)")
        
        self.restoreState()


class ReportGenerator:
    @staticmethod
    def _base64_to_temp_file(b64_str: str, suffix: str = ".jpg") -> str:
        """Decodes base64 string to a temporary file and returns the path."""
        if "," in b64_str:
            b64_str = b64_str.split(",")[1]
        data = base64.b64decode(b64_str)
        fd, path = tempfile.mkstemp(suffix=suffix)
        with os.fdopen(fd, 'wb') as tmp:
            tmp.write(data)
        return path

    @staticmethod
    def _generate_matplotlib_charts(result: Dict[str, Any], temp_dir: str) -> Dict[str, str]:
        """Generates matplotlib charts for the report."""
        paths = {}
        os.makedirs(temp_dir, exist_ok=True)

        # 1. Bar Chart: Disease Probability Distribution
        plt.figure(figsize=(6, 2.5))
        preds = result["disease_analysis"]["top_5_predictions"]
        diseases = [p["disease"] for p in preds][::-1]
        probs = [p["probability"] for p in preds][::-1]
        
        # Color palettes matching UI aesthetics
        colors_list = ['#10B981' if d == 'Healthy' else '#EF4444' if d == result["disease_analysis"]["disease_detected"] else '#3B82F6' for d in diseases]
        
        bars = plt.barh(diseases, probs, color=colors_list, height=0.55, edgecolor='#1e293b', linewidth=0.5)
        plt.title('Prediction Probability Distribution (%)', fontsize=10, fontweight='bold', pad=8, color='#1e293b')
        plt.xlabel('Probability (%)', fontsize=8, color='#475569')
        plt.xlim(0, 105)
        
        # Annotate values
        for bar in bars:
            width = bar.get_width()
            plt.text(width + 1.5, bar.get_y() + bar.get_height()/2, f'{width:.1f}%', 
                     va='center', ha='left', fontsize=7.5, fontweight='bold', color='#334155')

        plt.grid(True, axis='x', linestyle='--', alpha=0.3)
        plt.tight_layout()
        bar_path = os.path.join(temp_dir, "chart_prob.png")
        plt.savefig(bar_path, dpi=180)
        plt.close()
        paths["chart_prob"] = bar_path

        # 2. Donut Gauge: Plant Health Score
        plt.figure(figsize=(3, 3))
        health = result["crop_info"]["overall_health"]
        sizes = [health, 100 - health]
        colors_pie = ['#10b981', '#ef4444'] if health > 50 else ['#f59e0b', '#dc2626']
        
        plt.pie(
            sizes,
            colors=colors_pie,
            startangle=90,
            pctdistance=0.75,
            wedgeprops={'edgecolor': 'white', 'linewidth': 1.5}
        )
        # Draw center circle to make it a donut
        centre_circle = plt.Circle((0,0), 0.65, fc='white')
        fig = plt.gcf()
        fig.gca().add_artist(centre_circle)
        
        # Text in the middle
        plt.text(0, 0, f'{health}%\nHEALTH', horizontalalignment='center', verticalalignment='center',
                 fontsize=12, fontweight='bold', color='#1e293b')
        
        plt.title('Overall Plant Health Score', fontsize=10, fontweight='bold', pad=8, color='#1e293b')
        plt.tight_layout()
        health_path = os.path.join(temp_dir, "chart_health.png")
        plt.savefig(health_path, dpi=180)
        plt.close()
        paths["chart_health"] = health_path

        return paths

    @classmethod
    def generate_pdf(cls, result: Dict[str, Any], pdf_path: str):
        """Generates a professional multi-page ReportLab PDF scientific report."""
        temp_files = []
        
        # Create a workspace-local temp directory to hold images during compilation
        with tempfile.TemporaryDirectory() as temp_dir:
            try:
                # Decode base64 images to temp files
                orig_img_path = cls._base64_to_temp_file(result["original_image_base64"], suffix="_orig.jpg")
                mask_img_path = cls._base64_to_temp_file(result["mask_image_base64"], suffix="_mask.png")
                heatmap_img_path = cls._base64_to_temp_file(result["heatmap_image_base64"], suffix="_heat.jpg")
                
                temp_files.extend([orig_img_path, mask_img_path, heatmap_img_path])
                
                # Generate matplotlib charts
                charts = cls._generate_matplotlib_charts(result, temp_dir)
                temp_files.extend(list(charts.values()))

                # Setup ReportLab Document
                doc = SimpleDocTemplate(
                    pdf_path,
                    pagesize=letter,
                    rightMargin=54,
                    leftMargin=54,
                    topMargin=54,
                    bottomMargin=54
                )

                styles = getSampleStyleSheet()

                # Custom Styles matching clean agricultural theme (Emerald / Navy)
                title_style = ParagraphStyle(
                    'DocTitle',
                    parent=styles['Normal'],
                    fontName='Helvetica-Bold',
                    fontSize=24,
                    leading=30,
                    textColor=colors.HexColor("#064e3b"), # Deep Forest Green
                    alignment=0,
                    spaceAfter=10
                )
                
                subtitle_style = ParagraphStyle(
                    'DocSubtitle',
                    parent=styles['Normal'],
                    fontName='Helvetica',
                    fontSize=12,
                    leading=16,
                    textColor=colors.HexColor("#475569"),
                    alignment=0,
                    spaceAfter=25
                )

                h1_style = ParagraphStyle(
                    'SectionH1',
                    parent=styles['Heading1'],
                    fontName='Helvetica-Bold',
                    fontSize=14,
                    leading=18,
                    textColor=colors.HexColor("#065f46"),
                    spaceBefore=14,
                    spaceAfter=8,
                    keepWithNext=True
                )

                body_style = ParagraphStyle(
                    'BodyTextCustom',
                    parent=styles['Normal'],
                    fontName='Helvetica',
                    fontSize=9.5,
                    leading=13.5,
                    textColor=colors.HexColor("#1e293b")
                )

                body_bold_style = ParagraphStyle(
                    'BodyBoldCustom',
                    parent=body_style,
                    fontName='Helvetica-Bold'
                )

                meta_label_style = ParagraphStyle(
                    'MetaLabel',
                    parent=styles['Normal'],
                    fontName='Helvetica-Bold',
                    fontSize=9.5,
                    leading=13.5,
                    textColor=colors.HexColor("#475569")
                )

                recommendation_header_style = ParagraphStyle(
                    'RecHeader',
                    parent=styles['Normal'],
                    fontName='Helvetica-Bold',
                    fontSize=10,
                    leading=14,
                    textColor=colors.HexColor("#1f2937"),
                    spaceAfter=4
                )

                story = []

                # =========================================================================
                # PAGE 1: COVER PAGE
                # =========================================================================
                story.append(Spacer(1, 20))
                
                # Dynamic Decorative Accent Header
                accent_data = [[""]]
                accent_table = Table(accent_data, colWidths=[6.8 * inch], rowHeights=[10])
                accent_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#10b981")), # Bright Emerald
                ]))
                story.append(accent_table)
                story.append(Spacer(1, 40))

                # Logo Placeholder/Drawing (Green Leaf Path drawing or clean text representing logo)
                story.append(Paragraph("<b>AI CROP HEALTH SCENARIOS</b>", ParagraphStyle('LogoStyle', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=12, leading=14, textColor=colors.HexColor("#10b981"))))
                story.append(Spacer(1, 20))

                story.append(Paragraph("CROP HEALTH ANALYSIS REPORT", title_style))
                story.append(Paragraph("Scientific Diagnostic Evaluation & Precision Treatment Protocols", subtitle_style))
                story.append(Spacer(1, 30))

                # Large Cover Page Images (Original + Heatmap side by side)
                cover_imgs_data = [[
                    Image(orig_img_path, width=2.8 * inch, height=2.8 * inch),
                    Image(heatmap_img_path, width=2.8 * inch, height=2.8 * inch)
                ]]
                cover_imgs_table = Table(cover_imgs_data, colWidths=[3.4 * inch, 3.4 * inch])
                cover_imgs_table.setStyle(TableStyle([
                    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 10),
                ]))
                story.append(cover_imgs_table)
                story.append(Spacer(1, 40))

                # Cover Page Metadata Table
                meta_table_data = [
                    [Paragraph("Report ID:", meta_label_style), Paragraph(result["id"], body_bold_style),
                     Paragraph("Date & Time:", meta_label_style), Paragraph(result["timestamp"], body_style)],
                    [Paragraph("Crop Variety:", meta_label_style), Paragraph(result["crop_info"]["crop_type"], body_style),
                     Paragraph("Farm Location:", meta_label_style), Paragraph("Green Prairie Farm", body_style)],
                    [Paragraph("GPS Coordinates:", meta_label_style), Paragraph("42.368° N, -83.352° W", body_style),
                     Paragraph("Analysis Engine:", meta_label_style), Paragraph("ResNet-50 v4.1 (Foliar)", body_style)]
                ]
                meta_table = Table(meta_table_data, colWidths=[1.5 * inch, 2.0 * inch, 1.3 * inch, 2.0 * inch])
                meta_table.setStyle(TableStyle([
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                    ('TOPPADDING', (0,0), (-1,-1), 6),
                ]))
                story.append(meta_table)

                story.append(PageBreak())

                # =========================================================================
                # PAGE 2: ANALYSIS SUMMARY & DETAILED RESULTS
                # =========================================================================
                story.append(Paragraph("Diagnostic Summary", h1_style))
                story.append(Spacer(1, 5))

                # Parameters Table
                risk_level = "High" if result["yieldImpact"] > 25.0 else "Medium" if result["yieldImpact"] > 5.0 else "Low"
                params_data = [
                    [Paragraph("Parameter", meta_label_style), Paragraph("Value / Result", meta_label_style)],
                    [Paragraph("Crop Type", body_style), Paragraph(result["crop_info"]["crop_type"], body_style)],
                    [Paragraph("Classification Prediction", body_style), Paragraph(result["disease_analysis"]["disease_detected"], body_bold_style)],
                    [Paragraph("Scientific Pathogen Name", body_style), Paragraph(result["disease_analysis"]["scientific_name"], body_style)],
                    [Paragraph("Model Confidence", body_style), Paragraph(f"{result['disease_analysis']['confidence_score']}%", body_bold_style)],
                    [Paragraph("Disease Severity Index", body_style), Paragraph(f"{result['severity']}% ({result['disease_analysis']['severity_level']})", body_bold_style)],
                    [Paragraph("Crop Health Score", body_style), Paragraph(f"{result['crop_info']['overall_health']}/100", body_bold_style)],
                    [Paragraph("Estimated Yield Reduction", body_style), Paragraph(f"-{result['yieldImpact']}%", body_bold_style)],
                    [Paragraph("General Risk Category", body_style), Paragraph(risk_level, body_bold_style)]
                ]
                params_table = Table(params_data, colWidths=[3.2 * inch, 3.6 * inch])
                params_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (1,0), colors.HexColor("#f1f5f9")),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                    ('TOPPADDING', (0,0), (-1,-1), 6),
                    ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ]))
                story.append(params_table)
                story.append(Spacer(1, 15))

                # Visual Evidence thumbnails (3 images: Raw, Overlay Mask, Heatmap)
                story.append(Paragraph("Visual Evidence & Computer Vision Proofs", h1_style))
                story.append(Spacer(1, 5))
                
                evidence_data = [[
                    Image(orig_img_path, width=2.1 * inch, height=2.1 * inch),
                    Image(mask_img_path, width=2.1 * inch, height=2.1 * inch),
                    Image(heatmap_img_path, width=2.1 * inch, height=2.1 * inch)
                ], [
                    Paragraph("Original Leaf", meta_label_style),
                    Paragraph("Segmentation Mask", meta_label_style),
                    Paragraph("Grad-CAM Heatmap", meta_label_style)
                ]]
                
                evidence_table = Table(evidence_data, colWidths=[2.26 * inch, 2.26 * inch, 2.26 * inch])
                evidence_table.setStyle(TableStyle([
                    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('BOTTOMPADDING', (0,0), (2,0), 4),
                    ('BOTTOMPADDING', (0,1), (2,1), 10),
                ]))
                story.append(evidence_table)
                story.append(Spacer(1, 15))

                # AI Explanation Section
                story.append(Paragraph("AI Scientific Explanation", h1_style))
                story.append(Paragraph(result["ai_explanation"], body_style))
                
                story.append(PageBreak())

                # =========================================================================
                # PAGE 3: RECOMMENDATIONS & MATPLOTLIB CHARTS
                # =========================================================================
                story.append(Paragraph("Actionable Recommendations & Remedial Guidelines", h1_style))
                story.append(Spacer(1, 5))

                # Recommendations Container (stylized Box)
                recs = result["recommendations"]
                rec_box_data = [
                    [
                        Paragraph("⚡ IMMEDIATE ACTION PROTOCOL", recommendation_header_style),
                        Paragraph(recs["immediate_action"], body_style)
                    ],
                    [
                        Paragraph("🧪 SUGGESTED CHEMICAL TREATMENT", recommendation_header_style),
                        Paragraph(recs["fungicide_pesticide"], body_style)
                    ],
                    [
                        Paragraph("💧 IRRIGATION MATRIX PROTOCOL", recommendation_header_style),
                        Paragraph(recs["watering"], body_style)
                    ],
                    [
                        Paragraph("🌱 NUTRITIONAL PROGRAM REGIMEN", recommendation_header_style),
                        Paragraph(recs["fertilizer"], body_style)
                    ],
                    [
                        Paragraph("🚜 SOIL & SANITATION MANAGEMENT", recommendation_header_style),
                        Paragraph(recs["soil_management"], body_style)
                    ],
                    [
                        Paragraph("🛡️ LONG-TERM PREVENTION SYSTEM", recommendation_header_style),
                        Paragraph(recs["prevention_methods"], body_style)
                    ],
                    [
                        Paragraph("👁️ SCANNING & MONITORING FREQUENCY", recommendation_header_style),
                        Paragraph(recs["monitoring_frequency"], body_style)
                    ],
                ]
                
                rec_table = Table(rec_box_data, colWidths=[6.8 * inch])
                rec_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f0fdf4")), # Light green bg-green-50
                    ('BOX', (0,0), (-1,-1), 1.0, colors.HexColor("#bbf7d0")), # Border green-200
                    ('TOPPADDING', (0,0), (-1,-1), 6),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                    ('LEFTPADDING', (0,0), (-1,-1), 12),
                    ('RIGHTPADDING', (0,0), (-1,-1), 12),
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ]))
                story.append(rec_table)
                story.append(Spacer(1, 20))

                # Recharts/Matplotlib Section
                story.append(Paragraph("Statistical & Metric Visualizations", h1_style))
                story.append(Spacer(1, 5))

                charts_table_data = [[
                    Image(charts["chart_prob"], width=3.8 * inch, height=1.6 * inch),
                    Image(charts["chart_health"], width=2.4 * inch, height=2.4 * inch)
                ]]
                charts_table = Table(charts_table_data, colWidths=[4.2 * inch, 2.6 * inch])
                charts_table.setStyle(TableStyle([
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                ]))
                story.append(charts_table)
                story.append(Spacer(1, 15))

                # Academic References Section
                story.append(Paragraph("Verified Literature Citations", ParagraphStyle('RefHeader', parent=h1_style, fontSize=11, leading=14)))
                for ref in result["references"]:
                    story.append(Paragraph(f"• &nbsp; {ref}", ParagraphStyle('RefBullet', parent=body_style, leftIndent=15, firstLineIndent=-10)))

                # Build the PDF using NumberedCanvas
                doc.build(story, canvasmaker=NumberedCanvas)
            
            except Exception as ex:
                raise RuntimeError(f"Failed to compile PDF. Error: {str(ex)}")
            
            finally:
                # Clean up any files created in the global temporary list
                for path in temp_files:
                    try:
                        if os.path.exists(path):
                            os.remove(path)
                    except Exception:
                        pass

    @staticmethod
    def generate_csv(result: Dict[str, Any], csv_path: str):
        """Generates a CSV report summarizing the findings."""
        with open(csv_path, mode='w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(["Report ID", result["id"]])
            writer.writerow(["Timestamp", result["timestamp"]])
            writer.writerow(["Crop Type", result["crop_info"]["crop_type"]])
            writer.writerow(["Overall Health Score", result["crop_info"]["overall_health"]])
            writer.writerow(["Disease Detected", result["disease_analysis"]["disease_detected"]])
            writer.writerow(["Scientific Name", result["disease_analysis"]["scientific_name"]])
            writer.writerow(["Model Confidence (%)", result["disease_analysis"]["confidence_score"]])
            writer.writerow(["Severity Level", result["disease_analysis"]["severity_level"]])
            writer.writerow(["Severity Percentage (%)", result["severity"]])
            writer.writerow([])
            
            # Recommendations
            writer.writerow(["Recommendation Parameter", "Action Plan Guidelines"])
            for key, val in result["recommendations"].items():
                writer.writerow([key.replace("_", " ").title(), val])

    @staticmethod
    def generate_json(result: Dict[str, Any], json_path: str):
        """Generates a JSON report (excluding huge base64 images for size efficiency)."""
        clean_result = {k: v for k, v in result.items() if not k.endswith("_base64")}
        with open(json_path, mode='w', encoding='utf-8') as f:
            json.dump(clean_result, f, indent=2)
